### ISSUE TITLE
Lỗi SyntaxError: Unexpected identifier in \views\error.ejs while compiling ejs

### ISSUE THREAD

**Issue by HuyLeQuang2612** [shivaluma/Shop-nodejs-express-mongoose#17]
Tui bị một số lỗi nhưng xem nhiều trang vẫn không bik cách sửa hi vọng ad cho thêm ý kiến và hỗ trợ thêm chút chút. Cám ơn nhìu 

SyntaxError: Unexpected identifier in C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\views\error.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\ejs\lib\ejs.js:673:12)
    at Object.compile (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\ejs\lib\ejs.js:398:16)
    at handleCache (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\ejs\lib\ejs.js:235:18)
    at tryHandleCache (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\ejs\lib\ejs.js:274:16)
    at exports.renderFile [as engine] (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\ejs\lib\ejs.js:491:10)
    at View.render (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\express\lib\application.js:657:10)
    at Function.render (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\express\lib\application.js:609:3)
    at ServerResponse.render (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\express\lib\response.js:1039:7)
    at C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\app.js:84:7
    at Layer.handle_error (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\express\lib\router\index.js:326:13)
    at C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\express\lib\router\index.js:346:12)
    at next (C:\Users\acer\Desktop\Shop-nodejs-express-mongoose-master\node_modules\express\lib\router\index.js:280:10)
GET / 500 943.875 ms - -

**Comment by shivaluma** [comment]
bạn thử sử dụng những phiên bản nodejs cũ hơn xem, v10, v12, v14. Tại project này mình làm lâu rồi á nên nếu bạn dùng nodejs mới có thể bị lỗi
